spring.application.name=reservation
server.port=3010
spring.main.allow-circular-references= true
# ??? PostgreSQL ???????????????????????????????????????????????
spring.datasource.url=jdbc:postgresql://localhost:5432/ticket_reservation
spring.datasource.username=postgres
spring.datasource.password=hasnain3010?
spring.datasource.driver-class-name=org.postgresql.Driver

# ??? JPA ??????????????????????????????????????????????????????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# ??? Redis Cloud ??????????????????????????????????????????????
spring.data.redis.host=redis-17076.crce283.ap-south-1-2.ec2.cloud.redislabs.com
spring.data.redis.port=17076
spring.data.redis.password=QHCp4IZy1m2xo327K6eH1Yvekkth76hT
spring.data.redis.username=default

# ??? Cache ????????????????????????????????????????????????????
spring.cache.type=simple

# ??? Mail (Gmail) ?????????????????????????????????????????????
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vighiorazahasnain@gmail.com
spring.mail.password=gzec byjj rkay vbua
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ??? Stripe ???????????????????????????????????????????????????
stripe.secret.key=sk_test_51SBVr9DRIV9EVyvD2849lleX4nCEVrk8TkgnJ3ZXoxwIHFbrdYKHjR5D2iOqT19Z5Bogn9FoZ67f56jntlVGXnxn00JrMDXKEZ
stripe.publishable.key=pk_test_51SBVr9DRIV9EVyvDsJq69RKUGnOqwYd5bydXmwCkwwl1EaEEUMXX4TgfYiLX4OYZqmHsjPEpssI2yKYhQL75H7hP00QwBZuRF3

# ??? JWT ??????????????????????????????????????????????????????
jwt.secret=rwerfdsfgfhjiuytdgfbhjkuiytresfdghjuiytrefdvbvnhjkuytrdf
jwt.expiration=86400000

# ??? Logging ??????????????????????????????????????????????????
logging.level.org.hibernate.SQL=DEBUG
logging.level.system.ticket.reservation=DEBUG

# ??? Swagger ??????????????????????????????????????????????????
springdoc.swagger-ui.path=/swagger-ui.html

# Duffel API
duffel.api.url=https://api.duffel.com
duffel.api.token=duffel_test_KIMzu-KoOVRqemh3FW_yxeAliHv7zz1dgseonUdj7bw
duffel.api.version=v2
